### ISSUE TITLE
Where should we nom?

### ISSUE THREAD

**Issue by MylesBorins** [dimsumjs/nyc#1]
This will be the first dimsumJS in NYC

Where should we have it?

![Delicious Dim Sum](https://cloud.githubusercontent.com/assets/498775/18147593/63332d46-6fa3-11e6-81fc-18d3c7eb12a0.gif)

**Comment by janecakemaster** [comment]
gonna throw a wild one out there: https://www.yelp.com/biz/east-harbor-seafood-palace-brooklyn

**Comment by amycheng** [comment]
can confirm that this is my Dad's favorite spot
