### ISSUE TITLE
August Dim Sum: Sun. Aug. 19, 12:30PM

### ISSUE THREAD

**Issue by ehashman** [dimsumjs/nyc#12]
This month we're back in Manhattan Chinatown! Here are your options:

- Sun. Aug. 19 :smile: 
- Sun. Aug. 26 :tada: 
- Take a summer vacation?! (if other options get <5 votes) :heart:

**Comment by MylesBorins** [comment]
Oh no it is tied. Can we do it this Sunday?

**Comment by ehashman** [comment]
Agree, let's do this Sunday. I will send out tickets now.

**Comment by ehashman** [comment]
Tickets!! https://ti.to/dimsum-js/august-2018-nyc

**Comment by bellabie** [comment]
Too late to get in on this? (Do you have a reservation already?)

**Comment by ehashman** [comment]
There is no reservation, however the venue will probably need to change as we have too many people. So much for a quiet August 😂

Go grab a ticket on ti.to and stay tuned
