### ISSUE TITLE
September DimSum.js: Sun. Sep 30 @12:30pm

### ISSUE THREAD

**Issue by ehashman** [dimsumjs/nyc#13]
Poll time!

- ~Sun. Sep. 16 :smile:~
- Sun. Sep. 30 :tada:
- ~Sun. Sep. 23 :heart:~

**Comment by MylesBorins** [comment]
I'm out of town both weekends 😭

**Comment by ehashman** [comment]
Note: I have updated the poll to swap out Sat. 22nd for Sun. 30th since that only got one vote.

**Comment by ehashman** [comment]
Not enough votes for tomorrow, if we don't reach 5 on any given date we'll just take a break this month.

**Comment by ehashman** [comment]
Can we get one more person for Sep. 30?

**Comment by ehashman** [comment]
Sorry for the lack of organization this month; I can't make it this Sunday. @MylesBorins is picking things up this month if they end up happening.

**Comment by MylesBorins** [comment]
I think that with 4 people only coming Sunday it might make sense for us to just punt this month.  Sorry for the last minute shift everyone, have a great weekend!
