### ISSUE TITLE
December Dim Sum

### ISSUE THREAD

**Issue by ehashman** [dimsumjs/nyc#4]
I propose Sunday, Dec. 17!

**Comment by MylesBorins** [comment]
V in

**Comment by brianloveswords** [comment]
@ehashman what time are you thinking? I have metal shop in the morning (11am–2pm) so if you're planning on going after that (with enough time for me to get to the location) I'm down! But if you were planning on going earlier don't feel at all obligated to move things around on my behalf of course.

**Comment by ehashman** [comment]
I know @mylesborins can never make any time before noon so we should probably aim for after then... but I suspect if your schedule is looking at 2:30 or 3pm that's a little late. Perhaps you could meet us late or afterwards :)

Does noon-thirty otherwise work for people? Do we have venue suggestions? I think I heard a request for Dumpling Galaxy last month; if we do Queens maybe we should push to 1pm

**Comment by modernserf** [comment]
I’m in

**Comment by ehashman** [comment]
See you all tomorrow for noon-thirty at Dumpling Galaxy! I'll try to arrive first but.. weekend trains. I have me+2, Justin, and Myles currently; anyone else following please let me know if you're planning on joining :)

**Comment by modernserf** [comment]
Feeling under the weather today, not gonna make it to dumpling galaxy
