### ISSUE TITLE
January Dim Sum: Sat. Jan. 20 @12:30PM

### ISSUE THREAD

**Issue by ehashman** [dimsumjs/nyc#5]
Oops, I thought Myles posted this already.

Proposed dates:
- Saturday, Jan. 20 😄 
- Sunday, Jan. 21 if late (after 1pm) 🎉 
- Sunday, Jan. 28 ❤️ 

(vote with reactions)

**Comment by MylesBorins** [comment]
I can do this weekend 🎉

**Comment by ehashman** [comment]
We appear to have critical mass for this Saturday, Jan. 20th. Do people have a preference between Manhattan (Chinatown) and Brooklyn (Sunset Park?) dim sum? Plz comment if you do, I will try to come up with a new exciting place by tomorrow unless anyone else has suggestions!

**Comment by ehashman** [comment]
Okay, this month's venue is [Jing Fong](http://jingfongny.com/) in Manhattan's Chinatown. Let's meet at 12:30 noon. I'll try to be there a little early. Please let me know your +1's, etc. so I can put us in for the right number of people! If you didn't vote earlier please comment or otherwise reach out.

**Comment by modernserf** [comment]
@sarahmeyer this is like two blocks from your apartment, you should come
