### ISSUE TITLE
February Dim Sum: Sun. Feb. 18 @12:30PM

### ISSUE THREAD

**Issue by ehashman** [dimsumjs/nyc#6]
In Feburary we will have a special guest joining us!

Let's wait until March to go to Sunset Park. For February, let's return to :1st_place_medal::unicorn:

Please RSVP here or on Slack (there is a new #dimsumjs channel in the BoroJS slack!)

**Comment by MylesBorins** [comment]
I'm in!

**Comment by ehashman** [comment]
Reminder: this is happening tomorrow http://www.goldenunicornrestaurant.com/
