### ISSUE TITLE
March Dim Sum - Sun. Mar. 11th @12:30PM

### ISSUE THREAD

**Issue by ehashman** [dimsumjs/nyc#7]
Vote for your favourite date!

- Sun. Mar. 11 :heart: 
- Sat. Mar. 17 :tada: 
- Sun. Mar. 18 :smile:

**Comment by ehashman** [comment]
Oops, I can't read and mixed up the 11th and 18th. Let's meet in Brooklyn this time:

[East Harbor Seafood Palace](http://eastharborseafoodpalace.us/)

See you around 12:30pm on Sunday! I will try to get there early to start the wait.

**Comment by MylesBorins** [comment]
OH NO I DIDN'T SEE THE UPDATE AND I SLEPT IN
