### ISSUE TITLE
April Dim Sum: Sun. Apr. 29 @12:30PM

### ISSUE THREAD

**Issue by ehashman** [dimsumjs/nyc#8]
Vote with reactji!

- Sat. Apr. 14 :smile:  
- Sun. Apr. 15 :tada: 
- Sun. Apr. 29 :heart:

**Comment by ehashman** [comment]
We'll meet in Manhattan, venue TBD.

**Comment by ehashman** [comment]
Friends, we will be going to Nom Wah this month (Chinatown location): http://nomwah.com/chinatown

Please confirm either here, on Slack, or via some other means that you're still attending so I can get a headcount for the table!

**Comment by MylesBorins** [comment]
I am in

**Comment by shaoster** [comment]
I would like to join, with a +1.

**Comment by fhinkel** [comment]
Count me in!

**Comment by hackygolucky** [comment]
I'm in!

**Comment by groundwater** [comment]
I'm in, with a +1

**Comment by ehashman** [comment]
Hi all,

Due to extremely popular demand (current count is 14), we will need to switch venue as Nom Wah is too small. We will instead meet at Jing Fong Chinatown: http://jingfongny.com/

Same time, see you all there!

**Comment by ehashman** [comment]
@clinty and I are waiting outside Jing Fong. For those of you I don't know, I'm wearing a bunch of Brooklyn.JS pins on my jacket.

**Comment by groundwater** [comment]
ETA:

https://maps.app.goo.gl/lC6bmSprCOcBwrzs1

**Comment by ehashman** [comment]
We have now head inside Jing Fong. @shaoster @fhinkel

**Comment by nemx** [comment]
@ehashman, I mistakenly showed at Nom Wah. Currently en route to Jing Fong

**Comment by nemx** [comment]
showed*
Currently en route*

**Comment by nemx** [comment]
@ehashman, @fhinkel, @groundwater I've been walking around for a bit, but can't seem to find you guys
